meta_product_name: "Drug Dealer"
meta_title: "Drug Dealer - Focus on what matters while we do the rest"
meta_description: "DrugDealer is leading innovation in the market of medicine delivery."
meta_image: "medicine_photo.png" # should exist in `app/assets/images/`
twitter_account: "@drugdealer"   # required for Twitter Cards
